### ISSUE TITLE
预览图片报错

### ISSUE THREAD

**Issue by yejinjian** [crazyurus/miniprogram-action#4]
报错如下图所示
![image](https://github.com/crazyurus/miniprogram-action/assets/2288666/3f843424-fe72-4619-b131-8d94efa02bbc)
action配置是：
```
name: 小程序预览
on:
  push:
    branches:
      - develop
jobs:
  preview:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      
      - name: Run install
        run: yarn install --frozen-lockfile
      
      - name: Build production bundle
        run: yarn build
      
      - id: preview
        name: Compile
        uses: crazyurus/miniprogram-action@1.0.0
        with:
          action_type: preview
          project_path: './dist/build/mp-weixin'
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: QR Code
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Copy the following content to the address bar of the browser to open the preview QR code
            ```
            ${{ steps.preview.outputs.preview_qrcode }}
            ```
```
